<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>@if(isset($product->title)){{$product->title}}@endif</title>

        <!-- Meta tags -->
        <meta name="keywords" content="@if(isset($product->keywords)){{$product->keywords}}@endif">
        <meta name="description" content="@if(isset($product->description)){{$product->description}}@endif">
		<meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Meta tag generated by Laravel -->
		<meta name="csrf_token" content="{{ csrf_token() }}">

        <!-- Favicon -->
        <link rel="apple-touch-icon" href="{{url($app_public_url.$user['favicon'])}}">
        <link rel="icon" href="{{url($app_public_url.$user['favicon'])}}">

        @if($google_font !="")
        <!-- Google font -->
        <link href="{{$google_font}}" rel="stylesheet">
        @endif

        <!-- BOOTSTRAP AND FONT AWESOME  CSS -->
		<link rel="stylesheet" href="{{URL::asset('st-assets/bootstrap-3.3.7/css/bootstrap.min.css')}}">
		<link rel="stylesheet" href="{{URL::asset('st-assets/css/font-awesome-4.6.3/css/font-awesome.min.css')}}">

        <!-- PAGE CSS -->
        <link href="{{URL::asset('st-assets/css/style.css')}}" rel="stylesheet">
        <link href="{{url($app_public_url.'user/user-'.$user_id.'/css/user-'.$user_id.'.css')}}" rel="stylesheet">
        @yield('head')
    </head>
	<body>
		<!-- Navigation -->
		@include('site::partials.menu')


		@yield('content')

		<!-- /.container -->
		@include('site::partials.footer')
		<!-- Bootstrap core JavaScript
			================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
        <script src="{{URL::asset('st-assets/js/libs/jquery-3.1.1.min.js')}}"></script>
        <script src="{{URL::asset('st-assets/js/libs/jquery-ui.min.js')}}"></script>
        <script src="{{URL::asset('st-assets/js/libs/angular.min.js')}}"></script>
		<script src="{{URL::asset('st-assets/bootstrap-3.3.7/js/bootstrap.min.js')}}"></script>
		<script src="{{URL::asset('st-assets/js/libs/bootstrap-hover-dropdown.min.js')}}"></script>
		<script src="{{URL::asset('st-assets/js/libs/bootbox.min.js')}}"></script>
		@yield('scripts_js')
		@yield('slider')
		@yield('contactform')
	</body>
</html>